# Generated by Django 3.2.12 on 2023-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_Graph_Plotter', '0002_auto_20231103_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='x1_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='x2_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='x3_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='x_column',
            field=models.CharField(default='X', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='y_column',
            field=models.CharField(default='Y', max_length=255),
        ),
    ]
