# Generated by Django 3.2.12 on 2023-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_Graph_Plotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='x_column',
            field=models.CharField(default='x', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='y_column',
            field=models.CharField(default='y', max_length=255),
        ),
    ]
